### ISSUE TITLE
Latest Autofac (8.0.0) is not supported 

### ISSUE THREAD

**Issue by DmitryMak** [bugthesystem/Autofac.Extras.NLog#27]
Build warning on projects using latest Autofac:

`NU1608: Warning As Error: Detected package version outside of dependency constraint: Autofac.Extras.NLog 4.0.1 requires Autofac (>= 6.0.0 && < 8.0.0) but version Autofac 8.0.0 was resolved.`

**Comment by CNBoland** [comment]
This is fixed in release [v4.0.2](https://github.com/bugthesystem/Autofac.Extras.NLog/releases/tag/v4.0.2).
